language: java
sudo: required
jdk:
  - oraclejdk8
cache:  
  directories:  
   - $HOME/.m2  

before_install:
    - git clone --depth 1 https://github.com/kit-sdq/BuildUtilities.git /tmp/BuildUtilities
    - . /tmp/BuildUtilities/travis-ci/installMaven.sh
install: true

script: mvn clean verify

after_success:
- . /tmp/BuildUtilities/travis-ci/deploy.sh commons releng/edu.kit.ipd.sdq.commons.updatesite.aggregated final kit-sdq updatesite

notifications:
  slack:
    secure: DiNVzW2L9G3eOvw2LZmCi09UcYrbkBuswKRFp2DDULQo2cbUGy0X4Y/vr8KkdhHwf7LRFFYMkVIZIoWtUKW3KikSIIqCqc08ghHfgAL272lPfD7pfLfZVpYtTqKG1iKzp5UAmMcumeSotborYQJGpvKdSXouLRcZ5zdNL+gty/H0qIBmM0XDr+2qhoblR7FGKtkGtO+e0LQpk51BxxlYLrF8O8/vzdWMHNyy+EPCsVmk7SLEFLsNtfwl6x16yeUUkJpxCMTMI08U8DVh9wXJV0AChSD/sx8BkpshJpyB8UaastkkTmqtIFFYIplb3rDbUYetD5OqSk9A336Q+YJfYynqqQL3EuR1Ycet61TssomFrkVMShew8SQQ7r65AvPCK5dlLrkgQjno9zsmkXIGOKxEV1GRra7C+7Y33uUlgT4gNiK4GHQpiyJX7c5JoUiaxh2yS+7yR98/7yhLqA5vvUcRn47qTVTJBJUd87cwNVdIpVSM4vkNV40mEUxzC8qyCcv0QybjgMiQazExO3qTFTAvokpnvzZFb/3TA8EDev0esCyHq0q+AJGPMaCV75iXFO9YexFX8/LsufEIsGVyKRgnALYVO3zfQ4DlGhataMvNmUTEUkFiXJ92ekEmQS/DHXLDmLF8SJknfcHPD1Rub6IvHjuYetbOsA9eVSilQek=